奇异值分解svd 
SVD 中的「右奇异向量矩阵 V」：其列向量就是 PCA 中的「主成分（PC）」—— 每一列对应一个主成分（如 V 的第 1 列是 PC1，第 2 列是 PC2）；SVD 中的「奇异值 \(\sigma_i\)」：与 PCA 中「主成分的方差解释比例」直接相关 —— 奇异值的平方（\(\sigma_i^2\)）除以所有奇异值平方和（\(\sum \sigma_j^2\)），就是第 i 个主成分（PCi）解释的方差比例。

In [1]:
import numpy as np
from numpy.linalg import svd

a = np.array([[1,0,1],[0,1,1],[0,0,0]])
u,s,vt = svd(a)
print(u); print(s); print(vt)

[[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]
[1.73205081 1.         0.        ]
[[ 4.08248290e-01  4.08248290e-01  8.16496581e-01]
 [-7.07106781e-01  7.07106781e-01  2.22044605e-16]
 [-5.77350269e-01 -5.77350269e-01  5.77350269e-01]]
